name: Estate
favicon: null
layout_spectrum: 0.0858871832024306
typography_spectrum: 0.4748469120822847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3573963991366327
  lightness: 0.8968107365071774
  saturation: 0.4890437514986843
  rhythmicContrast: 0.43834141409024596
purpose: []
